Areas/RoomInformation/Controllers/RoomTypeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HotelApplication.Models;
using Microsoft.AspNetCore.Http;
using HotelApplication.Services.Interface;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using HotelApplication.Database;

namespace HotelApplication.Areas.RoomInformation.Controllers
{
    [Area("RoomInformation")]
    public class RoomTypeController : Controller
    {
        private readonly IRoomInformation<RoomType> service;
        private readonly HotelDBContext context;
        private readonly IHostingEnvironment hostingEnvironment;

        public RoomTypeController(HotelDBContext context,
            IRoomInformation<RoomType> service,
            IHostingEnvironment hostingEnvironment)
        {
            this.context = context;
            this.service = service;
            this.hostingEnvironment = hostingEnvironment;
        }

        public async Task<IActionResult> Index()
        {
            RoomType data = new RoomType
            {
                RoomTypes = await service.Get()
            };
            return View(data);
        }

        public async Task<IActionResult> Save(RoomType model)
        {
            RoomType roomType = new RoomType();
            if (model.Id != 0)
            {
                roomType = await service.Details(model.Id);
            }
            roomType.RoomTypes = await service.Get();
            return View(roomType);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Save(RoomType model, IFormFile Files)
        {
            if (ModelState.IsValid)
            {
                if(Files != null)
                {
                    string folder = "images/roomtype/";
                    folder += Guid.NewGuid().ToString() + Files.FileName;
                    string serverFolder = Path.Combine(hostingEnvironment.WebRootPath, folder);
                    model.ImageUrl = "/" + folder;
                    await Files.CopyToAsync(new FileStream(serverFolder, FileMode.Create));
                }
                if (model.Id == 0)
                {
                    await service.Post(model);
                }
                else
                {
                    await service.Edit(model);
                }
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        public async Task<IActionResult> Details(int id = 0)
        {
            return View(await service.Details(id));
        }

        public async Task<IActionResult> Delete(int id)
        {
            var roomType = await context.RoomTypes.FindAsync(id);
            await service.Delete(roomType);
            return RedirectToAction(nameof(Index));
        }
    }
}

Areas/RoomInformation/Views/RoomType/Details.cshtml
@model HotelApplication.Models.RoomType

@{
    ViewData["Title"] = "Details";
    Layout = null;
}
<h4>Room Type Details</h4>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-4"> @Html.DisplayNameFor(model => model.RoomTypeName) </dt>
        <dd class="col-sm-8"> @Html.DisplayFor(model => model.RoomTypeName) </dd>
        <dt class="col-sm-4"> @Html.DisplayNameFor(model => model.BasePrice) </dt>
        <dd class="col-sm-8"> @Html.DisplayFor(model => model.BasePrice) </dd>
        <dt class="col-sm-4"> @Html.DisplayNameFor(model => model.Description) </dt>
        <dd class="col-sm-8"> @Html.DisplayFor(model => model.Description) </dd>
        <dt class="col-sm-4"> @Html.DisplayNameFor(model => model.ImageUrl) </dt>
        <dd class="col-sm-8"> <img src="@Model.ImageUrl" alt="Photo" style="width:200px; border-radius:5px;" /> </dd>
    </dl>
</div>

Areas/RoomInformation/Views/RoomType/Index.cshtml
@model HotelApplication.Models.RoomType

@{
    ViewData["Title"] = "Room Catagory List";
}

<div class="row">
    <div class="col-md-6">
        <h3 class="h3">Room Catagory</h3>
    </div>
    <div class="col-md-6">
        <div style="text-align:right;">
            <a asp-action="Save" class="btn btn-primary" style="width:300px;"><i class='bx bx-plus'></i> Room Catagory</a>
        </div>
    </div>
</div>

<table class="table table-striped" style="margin-top:30px">
    <thead>
        <tr>
            <th> SL. </th>
            <th> @Html.DisplayNameFor(x => x.RoomTypeName) </th>
            <th> @Html.DisplayNameFor(x => x.BasePrice) </th>
            <th> @Html.DisplayNameFor(x => x.Description) </th>
            <th class="text-center">Action</th>
        </tr>
    </thead>
    <tbody>
        @{
            var i = 1;
            foreach (var item in Model.RoomTypes)
            {
                <tr>
                    <td> @i. </td>
                    <td> @Html.DisplayFor(modelItem => item.RoomTypeName) </td>
                    <td> @Html.DisplayFor(modelItem => item.BasePrice) </td>
                    <td> @Html.DisplayFor(modelItem => item.Description) </td>
                    <td class="text-center">
                        <a class="btn btn-sm btn-success" asp-action="Save" asp-route-id="@item.Id"><i class='bx bx-edit'></i></a> |
                        <a class="btn btn-sm btn-info text-white" onclick="showInPopup('@Url.Action("Details", "RoomType", new { id = item.Id }, Context.Request.Scheme)')"><i class='bx bx-info-circle'></i></a> |
                        <a class="btn btn-sm btn-danger" onclick="Delete(@item.Id)" href="#"><i class='bx bx-trash'></i></a>
                    </td>
                </tr>
                i++;
            }
        }
    </tbody>
</table>

<script>
    function Delete(id) {
        location.replace("/RoomInformation/RoomType/Delete/" + id);
    }
</script>

Areas/RoomInformation/Views/RoomType/Save.cshtml
@model HotelApplication.Models.RoomType

@{
    ViewData["Title"] = "Save";
}

<div class="row">
    <div class="col-md-1">
        <a asp-action="Index" class="btn btn-light" style="border-radius:50%"><i class='bx bx-arrow-back'></i></a>
    </div>
    <div class="col-md-5">
        <h3 class="h3">Add Room Catagory</h3>
    </div>
</div>

<div class="container">
    <form asp-action="Save" enctype="multipart/form-data">
        <hr />
        <div class="row">
            <div class="col-md-8">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Id" id="id" />

                <div class="row form-group">
                    <label asp-for="RoomTypeName" class="col-sm-3 control-label"></label>
                    <div class="col-sm-9">
                        <input asp-for="RoomTypeName" class="form-control" id="roomTypeName" />
                    </div>
                    <span asp-validation-for="RoomTypeName" class="text-danger"></span>
                </div>

                <div class="row form-group">
                    <label asp-for="BasePrice" class="col-sm-3 control-label"></label>
                    <div class="col-sm-9">
                        <input asp-for="BasePrice" class="form-control" id="basePrice" />
                    </div>
                    <span asp-validation-for="BasePrice" class="text-danger"></span>
                </div>
                <div class="row form-group">
                    <label asp-for="Description" class="col-sm-3 control-label"></label>
                    <div class="col-sm-9">
                        <textarea asp-for="Description" class="form-control" id="description"></textarea>
                    </div>
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="row form-group">
                    <label asp-for="ImageUrl" class="col-sm-3 control-label"></label>
                    <input asp-for="ImageUrl" type="hidden" class="form-control" id="imageUrl" />
                    <div class="col-sm-9">
                        <input type="file" name="Files" accept="image/jpeg, image/png" onchange="Preview(this, document.getElementById('imagePreview'))" class="form-control-file img-thumbnail" />
                    </div>
                    <span asp-validation-for="ImageUrl" class="text-danger"></span>
                </div>
            </div>

            <div class="col-md-4">
                <div class="form-group text-center">
                    <img src="@Model.ImageUrl" alt="Photo" class=" img-thumbnail float-right" style="width:225px;" id="imagePreview" />
                </div>
            </div>
        </div>
        <hr />
        <div class="form-group" style="text-align:center;">
            <input type="submit" value="Save" class="col-sm-9 btn btn-primary" style="border-radius:50px;" />
        </div>
    </form>
</div>