Models/Invoice.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace HotelApplication.Models
{
    public class Invoice
    {
        public int Id { get; set; }

        [Display(Name = "Invoice Number")]
        public int InvoiceNumber { get; set; }

        public int BookingId { get; set; }
        public Booking Booking { get; set; }

        public int SuplementaryId { get; set; }
        public IEnumerable<Suplementary> Suplementary { get; set; }

        public int ComplementaryId { get; set; }
        public IEnumerable<Complementary> Complementary { get; set; }

        [Column(TypeName = "decimal(18,2)")]
        public decimal? Amount { get; set; }

        [Column(TypeName = "decimal(18,2)")]
        public decimal? VAT { get; set; }

        [Display(Name = "Paid Amount")]
        [Column(TypeName = "decimal(18,2)")]
        public decimal? PaidAmount { get; set; }

        [Display(Name = "Due Amount")]
        [Column(TypeName = "decimal(18,2)")]
        public decimal? DueAmount { get; set; }

        [Display(Name = "Total Amount")]
        [Column(TypeName = "decimal(18,2)")]
        public decimal? TotalAmount { get; set; }

        public string Status { get; set; }

        [NotMapped]
        public IEnumerable<Invoice> Invoices { get; set; }

        [NotMapped]
        public IEnumerable<Booking> Bookings { get; set; }
    }
}

Areas/Bookings/Controllers/BookingController.cs
using HotelApplication.Models;
using HotelApplication.Services.Interface;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HotelApplication.Database;

namespace HotelApplication.Areas.Bookings.Controllers
{
    [Area("Bookings")]
    public class BookingController : Controller
    {
        private readonly IRoomInformation<Booking> service;
        private readonly IBooking<Booking> bookingServices;
        private readonly HotelDBContext context;
        private readonly IHostingEnvironment hostingEnvironment;

        public BookingController(HotelDBContext context,
            IRoomInformation<Booking> service,
            IBooking<Booking> bookingServices,
            IHostingEnvironment hostingEnvironment)
        {
            this.context = context;
            this.service = service;
            this.bookingServices = bookingServices;
            this.hostingEnvironment = hostingEnvironment;
        }

        public async Task<IActionResult> Index()
        {
            Booking booking = new Booking
            {
                ListOfRoomBooking = service.GetAllRoomsAndRoomTypes(),
                Bookings = await service.Get()
            };

            foreach (var x in booking.ListOfRoomBooking.Rooms as IEnumerable<Room>)
            {
                foreach (var y in booking.ListOfRoomBooking.BookingList as IEnumerable<Booking>)
                {
                    if (y.RoomId == x.Id && y.CheckIn <= DateTime.UtcNow && y.CheckOut >= DateTime.UtcNow)
                    {
                        x.Available = false;
                        break;
                    }
                    else
                    {
                        x.Available = true;
                    }
                }
                if(booking.ListOfRoomBooking.BookingList.Count == 0)
                {
                    x.Available = true;
                }
            }
            await context.SaveChangesAsync();
            return View(booking);
        }

        public async Task<IActionResult> Save(int id)
        {
            Booking booking = new Booking();
            booking.Room = await context.Rooms.Where(x => x.Id == id).FirstOrDefaultAsync();
            booking.RoomNo = booking.Room.RoomNumber;
            booking.RoomId = booking.Room.Id;

            ViewData["Suplementary"] = bookingServices.PopulateSelectedSuplementaryServices(booking);
            ViewData["Complementary"] = bookingServices.PopulateSelectedComplementaryServices(booking);
            ViewData["ApplicationUserId"] = new SelectList(context.Users, "Id", "Id", booking.ApplicationUserId);
            return View(booking);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Save(Booking model, int[] SelectedSuplementaryIDs, int[] SelectedComplementaryIDs)
        {
            if (ModelState.IsValid)
            {
                if (model.BookingId == 0)
                {
                    model.Quantity = ((model.CheckOut.Date - model.CheckIn.Date).Days) + 1;
                    model.TotalAmount = model.Amount * model.Quantity;
                    await service.Post(model);
                }
                else
                {
                    model.Quantity = ((model.CheckOut.Date - model.CheckIn.Date).Days) + 1;
                    model.TotalAmount = model.Amount * model.Quantity;
                    await service.Edit(model);
                }
                bookingServices.UpdateBookingSuplementaryList(model, SelectedSuplementaryIDs);
                bookingServices.UpdateBookingComplementaryList(model, SelectedComplementaryIDs);
                return RedirectToAction(nameof(BookingList));
            }
            return View(model);
        }

        public async Task<IActionResult> Edit(int id)
        {
            Booking booking = new Booking();
            if (id != 0)
            {
                booking = await service.Details(id);
                ViewData["Suplementary"] = bookingServices.PopulateSelectedSuplementaryServices(booking);
                ViewData["Complementary"] = bookingServices.PopulateSelectedComplementaryServices(booking);
                return View(booking);
            }
            ViewData["Suplementary"] = bookingServices.PopulateSelectedSuplementaryServices(booking);
            ViewData["Complementary"] = bookingServices.PopulateSelectedComplementaryServices(booking);
            ViewData["ApplicationUserId"] = new SelectList(context.Users, "Id", "Id", booking.ApplicationUserId);
            return View(booking);
        }

        public async Task<IActionResult> BookingList()
        {
            Booking data = new Booking
            {
                Bookings = await service.Get()
            };
            return View(data);
        }

        public async Task<IActionResult> Details(int id)
        {
            if (id == 0)
            {
                return NotFound();
            }
            var booking = await service.Details(id);
            if (booking == null)
            {
                return NotFound();
            }
            booking.Room = context.Rooms.Where(x => x.Id == booking.RoomId).FirstOrDefault();
            booking.Room.RoomType = context.RoomTypes.Where(x => x.Id == booking.Room.RoomTypeId).FirstOrDefault();
            var ImagesAndFeatures = await service.GetRoomFeaturesAndImages(booking.Room);
            ViewData["Features"] = ImagesAndFeatures.Features;
            ViewData["Images"] = ImagesAndFeatures.Images;

            var SuplementaryAndComplementary = await bookingServices.GetBookingSuplementaryAndComplementary(booking);
            ViewData["Suplementaries"] = SuplementaryAndComplementary.Suplementaries;
            ViewData["Complementaries"] = SuplementaryAndComplementary.Complementaries;
            return View(booking);
        }

        public async Task<IActionResult> Delete(int id)
        {
            var data = await context.Bookings.FindAsync(id);
            await service.Delete(data);
            return RedirectToAction(nameof(BookingList));
        }
    }
}

Areas/Bookings/Controllers/InvoiceController.cs
using HotelApplication.Database;
using HotelApplication.Models;
using HotelApplication.Services.Interface;
using HotelApplication.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HotelApplication.Areas.Bookings.Controllers
{
    [Area("Bookings")]
    public class InvoiceController : Controller
    {
        private readonly IRoomInformation<Invoice> service;
        private readonly IBooking<Invoice> bookingServices;
        private readonly HotelDBContext context;
        private decimal vat = 7.5M;

        public InvoiceController(HotelDBContext context,
            IRoomInformation<Invoice> service,
            IBooking<Invoice> bookingServices)
        {
            this.context = context;
            this.service = service;
            this.bookingServices = bookingServices;
        }

        public async Task<IActionResult> Index()
        {
            Booking data = new Booking
            {
                Bookings = await context.Bookings.ToListAsync()
            };
            return View(data);
        }

        public async Task<IActionResult> Save(int id)
        {
            Invoice data = new Invoice
            {
                Booking = await context.Bookings.FindAsync(id),
                Suplementary = bookingServices.InvoiceSuplementary(id),
                Complementary = bookingServices.InvoiceComplementary(id)
            };

            var maxInvNo = context.Invoices.AsNoTracking().Max(x => x.InvoiceNumber);
            if(maxInvNo == 0)
            {
                maxInvNo = 1000;
            }
            data.InvoiceNumber = maxInvNo + 1;

            data.BookingId = data.Booking.BookingId;
            data.Amount = data.Booking.TotalAmount;
            foreach (var item in data.Suplementary)
            {
                data.Amount += item.TotalAmount;
            }

            data.VAT = data.Amount * (vat / 100);
            data.TotalAmount = data.Amount + data.VAT;
            return View(data);
        }

        public IActionResult InvoiceList()
        {
            var data = bookingServices.GetAllInvoiceAndBooking();
            return View(data);
        }

        [HttpPost]
        public async Task<IActionResult> PaymentMethod(Invoice model)
        {
            if (ModelState.IsValid)
            {
                if (model.Id == 0)
                {
                    await service.Post(model);
                }
            }
            return View();
        }

        public async Task<IActionResult> PaymentSuccess(Invoice model)
        {
            return View();
        }
    }
}

Areas/Bookings/Views/Invoice/Index.cshtml
@model HotelApplication.Models.Booking

@{
    ViewData["Title"] = "Guest";
}

<div class="row">
    <div class="col-md-6">
        <h3 class="h3">List for Invoice</h3>
    </div>
    <div class="col-md-6" style="text-align:right">
        <a class="btn btn-sm btn-info text-white" asp-action="InvoiceList"><i class='bx bx-list-ol'></i> Invoice List</a>
    </div>
</div><hr />

<table class="table table-striped" style="margin-top:30px" id="myTable">
    <thead>
        <tr>
            <th> SL. </th>
            <th> @Html.DisplayNameFor(x => x.CustomerName) </th>
            <th> @Html.DisplayNameFor(x => x.CustomerPhone) </th>
            <th> @Html.DisplayNameFor(x => x.Quantity) </th>
            <th> @Html.DisplayNameFor(x => x.Amount) </th>
            <th> @Html.DisplayNameFor(x => x.TotalAmount) </th>
            <th class="text-center">Action</th>
        </tr>
    </thead>
    <tbody>
        @{
            var i = 1;
            foreach (var item in Model.Bookings)
            {
                <tr>
                    <td> @i. </td>
                    <td> @Html.DisplayFor(modelItem => item.CustomerName) </td>
                    <td> @Html.DisplayFor(modelItem => item.CustomerPhone) </td>
                    <td> @Html.DisplayFor(modelItem => item.Quantity) </td>
                    <td> @Html.DisplayFor(modelItem => item.Amount) </td>
                    <td> @Html.DisplayFor(modelItem => item.TotalAmount) </td>
                    <td class="text-center">
                        <a class="btn btn-sm btn-success" asp-controller="Invoice" asp-action="Save" asp-route-id="@item.BookingId"><i class='bx bx-plus'></i> Invoice</a> |
                        <a class="btn btn-sm btn-info text-white" onclick="showInPopup('@Url.Action("Details", "Booking", new { id = item.BookingId }, Context.Request.Scheme)')"><i class='bx bx-info-circle'></i></a>
                    </td>
                </tr>
                i++;
            }
        }
    </tbody>
</table>


<script src="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/alertify.min.js"></script>
<script type="text/javascript">
    function Delete(id) {
        location.replace("/Bookings/Booking/Delete/" + id);
    }

    $(document).ready(function () {
        $('#myTable').DataTable({

        });
    });

</script>

Areas/Bookings/Views/Invoice/InvoiceList.cshtml
@model HotelApplication.ViewModel.InvoiceAdminIndexViewModel

@{
    ViewData["Title"] = "Booking List for Billing";
}

<div class="row">
    <div class="row">
        <div class="col-md-3">
            <a asp-action="Index" class="btn btn-light" style="border-radius:50%"><i class='bx bx-arrow-back'></i></a>
        </div>
        <div class="col-md-9">
            <h3 class="h3">Invoice List</h3>
        </div>
    </div>
</div>

<table class="table table-striped" style="margin-top:30px" id="myTable">
    <thead>
        <tr>
            <th> SL. </th>
            <th> Invoice Number</th>
            <th> Name </th>
            <th> Phone </th>
            <th> Paid Amount </th>
            <th> Due Amount </th>
            <th> Total Amount </th>
            <th class="text-center">Action</th>
        </tr>
    </thead>
    <tbody>
        @{
            var i = 1;
            foreach (var item in Model.Invoices)
            {
                <tr>
                    <td> @i. </td>
                    <td> @Html.DisplayFor(modelItem => item.InvoiceNumber) </td>
                    <td> @Html.DisplayFor(modelItem => item.Booking.CustomerName) </td>
                    <td> @Html.DisplayFor(modelItem => item.Booking.CustomerPhone) </td>
                    <td> @Html.DisplayFor(modelItem => item.PaidAmount) </td>
                    <td> @Html.DisplayFor(modelItem => item.DueAmount) </td>
                    <td> @Html.DisplayFor(modelItem => item.TotalAmount) </td>
                    <td class="text-center">
                        <a class="btn btn-sm btn-success" asp-action="Edit" asp-route-id="@item.BookingId"><i class='bx bx-edit'></i></a> |
                        <a class="btn btn-sm btn-info text-white" onclick="showInPopup('@Url.Action("Details", "Booking", new { id = item.BookingId }, Context.Request.Scheme)')"><i class='bx bx-info-circle'></i></a> |
                        <a class="btn btn-sm btn-danger" onclick="Delete(@item.BookingId)" href="#"><i class='bx bx-trash'></i></a>
                    </td>
                </tr>
                i++;
            }
        }
    </tbody>
</table>

<script src="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/alertify.min.js"></script>
<script type="text/javascript">
    function Delete(id) {
        location.replace("/Bookings/Booking/Delete/" + id);
    }

    $(document).ready(function () {
        $('#myTable').DataTable({
            dom: 'Bfrtip',
            buttons: [
                'pdf', 'copy', 'excel', 'print', 'csv'
            ]
        });
    });

</script>

Areas/Bookings/Views/Invoice/PaymentMethod.cshtml
@{
    ViewData["Title"] = "PaymentMethod";
}

<h1 class="display-4" style="margin-left:30px; margin-top:30px;" >Payment Method</h1>



<div class="row" style="margin:30px">
    <div class="card mb-3 shadow-sm" style="padding: 20px; margin-right: 15px;" id="payment">
        <a asp-action="PaymentSuccess" asp-controller="Invoice" asp-area="Bookings" id="nameColor">
            <div class="row">
                <img src="/images/paymentGetway/cash.jpg" alt="Cash" class="col-md-6" style="width:200px; height:100px;" />
                <div class="card-body col-md-6">
                    <h1 class="h1 card-title">Cash</h1>
                </div>
            </div>
        </a>
    </div>
    <div class="card mb-3 shadow-sm" style="padding: 20px; margin-right: 15px;" id="payment">
        <a asp-action="PaymentSuccess" asp-controller="Invoice" asp-area="Bookings" id="nameColor">
            <div class="row">
                <img src="/images/paymentGetway/bkash.png" alt="Bkash" class="col-md-5" style="width:200px; height:100px;" />
                <div class="card-body col-md-7">
                    <h1 class="h1 card-title">Bkash</h1>
                </div>
            </div>
        </a>
    </div>
    <div class="card mb-3 shadow-sm" style="padding: 20px; margin-right: 15px; " id="payment">
        <a asp-action="PaymentSuccess" asp-controller="Invoice" asp-area="Bookings" id="nameColor">
            <div class="row">
                <img src="/images/paymentGetway/nagad.png" alt="Nagad" class="col-md-5" style="width:180px; height:100px;" />
                <div class="card-body col-md-7">
                    <h1 class="h1 card-title">Nagad</h1>
                </div>
            </div>
        </a>
    </div>
    <div class="card mb-3 shadow-sm" style="padding: 20px; margin-right: 15px; " id="payment">
        <a asp-action="PaymentSuccess" asp-controller="Invoice" asp-area="Bookings" id="nameColor">
            <div class="row">
                <img src="/images/paymentGetway/rocket.png" alt="Rocket" class="col-md-5" style="width:200px; height:100px;" />
                <div class="card-body col-md-7">
                    <h1 class="h1 card-title">Rocket</h1>
                </div>
            </div>
        </a>
    </div>
    <div class="card mb-3 shadow-sm" style="padding: 20px; margin-right: 15px; " id="payment">
        <a asp-action="PaymentSuccess" asp-controller="Invoice" asp-area="Bookings" id="nameColor">
            <div class="row">
                <img src="/images/paymentGetway/card.png" alt="Card" class="col-md-4" style="width:300px; height:100px;" />
                <div class="card-body col-md-8">
                    <h1 class="h1 card-title">Card</h1>
                </div>
            </div>
        </a>
    </div>
</div>

Areas/Bookings/Views/Invoice/PaymentSuccess.cshtml
@{
    ViewData["Title"] = "PaymentSuccess";
}

<link href="https://fonts.googleapis.com/css?family=Nunito+Sans:400,400i,700,900&display=swap" rel="stylesheet">

<div class="card">
    <div style="border-radius:200px; height:200px; width:200px; background: #F8FAF5; margin:0 auto;">
        <i class="checkmark">✓</i>
    </div>
    <h1 id="paymentSuccessfull">Payment Successfull</h1>
    <p id="p">Thank you for your payment<br /> Invoice Number </p>
    <a asp-action="Index" asp-controller="Booking" asp-area="Bookings" style="text-decoration:none;">Back to Home</a>
</div>

<style>
    #contain {
        text-align: center;
        padding: 40px 0;
    }

    #paymentSuccessfull {
        color: #88B04B;
        font-family: "Nunito Sans", "Helvetica Neue", sans-serif;
        font-weight: 900;
        font-size: 40px;
        margin-bottom: 10px;
    }

    #p {
        color: #404F5E;
        font-family: "Nunito Sans", "Helvetica Neue", sans-serif;
        font-size: 20px;
        margin: 0;
    }

    .checkmark {
        color: #9ABC66;
        font-size: 100px;
        line-height: 200px;
        margin-left: -15px;
    }

    .card {
        background: white;
        padding: 60px;
        border-radius: 4px;
        box-shadow: 0 2px 3px #C8D0D8;
        display: inline-block;
        margin: 0 auto;
    }
</style>

Areas/Bookings/Views/Invoice/Save.cshtml
@model HotelApplication.Models.Invoice

@{
    ViewData["Title"] = "Save";
}

<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />
<link href="~/css/invoice.css" rel="stylesheet" />

<div class="page-content container">
    <div class="page-header text-blue-d2">
        <h1 class="page-title text-secondary-d1">
            Invoice
            <small class="page-info" id="invoiceNo">
                <i class="fa fa-angle-double-right text-80"></i>
                ID: #@Model.InvoiceNumber
            </small>
        </h1>

        <div class="row">
            <div class="col-12">
                <div class="text-center text-150">
                    <i class="fa fa-book fa-2x text-success-m2 mr-1"></i>
                    <span class="text-default-d3">GRAND HOTEL</span>
                </div>
            </div>
        </div>

        <div class="page-tools">
            <div class="action-buttons">
                <a class="btn bg-white btn-light mx-1px text-95" href="#" data-title="Print">
                    <i class="mr-1 fa fa-print text-primary-m1 text-120 w-2"></i>
                    Print
                </a>
                <a class="btn bg-white btn-light mx-1px text-95" href="#" data-title="PDF">
                    <i class="mr-1 fa fa-file-pdf-o text-danger-m1 text-120 w-2"></i>
                    Export
                </a>
            </div>
        </div>
    </div>

    <div class="container px-0">
        <div class="row mt-4">
            <div class="col-12 col-lg-12">
                <form asp-action="PaymentMethod" method="post">
                    <input asp-for="Id" value="0" type="hidden" />
                    <input asp-for="BookingId" type="hidden" />
                    <input asp-for="InvoiceNumber" type="hidden" />
                    <input asp-for="Amount" type="hidden" />
                    <input asp-for="VAT" type="hidden" />
                    <input asp-for="TotalAmount" type="hidden" />

                    <div class="row">
                        <div class="col-sm-6">
                            <div>
                                <span class="text-sm text-grey-m2 align-middle">To:</span>
                                <span class="text-600 text-110 text-blue align-middle" id="name">@Model.Booking.CustomerName</span>
                            </div>
                            <div class="text-grey-m2">
                                <div class="my-1">
                                    <span class="text-sm text-grey-m2 align-middle" id="phone">@Model.Booking.CustomerPhone</span>
                                </div>
                                <div class="my-1">
                                    <span class="text-sm text-grey-m2 align-middle" id="email">@Model.Booking.CustomerEmail</span>
                                </div>
                                <div class="my-1">
                                    <span class="text-sm text-grey-m2 align-middle" id="address">@Model.Booking.CustomerAddress</span>
                                </div>
                            </div>
                        </div>
                        <!-- /.col -->

                        <div class="text-95 col-sm-6 align-self-start d-sm-flex justify-content-end">
                            <hr class="d-sm-none" />
                            <div class="text-grey-m2">
                                <div class="mt-1 mb-2 text-secondary-m1 text-600 text-125">
                                    Invoice
                                </div>

                                <div class="my-2"><i class="fa fa-circle text-blue-m2 text-xs mr-1"></i> <span class="text-600 text-90">ID:</span> #@Model.InvoiceNumber</div>

                                <div class="my-2" id="issueDate"><i class="fa fa-circle text-blue-m2 text-xs mr-1"></i> <span class="text-600 text-90">Issue Date:</span> @DateTime.Now</div>

                                <div class="my-2" id="status"><i class="fa fa-circle text-blue-m2 text-xs mr-1"></i> <span class="text-600 text-90">Status:</span> <span class="badge badge-warning badge-pill px-25">@Model.Status</span></div>
                            </div>
                        </div>
                        <!-- /.col -->
                    </div>

                    <div class="mt-4">
                        <div class="row text-600 text-white bgc-default-tp1 py-25">
                            <div class="d-none d-sm-block col-1">#</div>
                            <div class="col-9 col-sm-5">Description</div>
                            <div class="d-none d-sm-block col-4 col-sm-2">Qty</div>
                            <div class="d-none d-sm-block col-sm-2">Unit Price</div>
                            <div class="col-2">Amount</div>
                        </div>

                        <div class="text-95 text-secondary-d3">
                            <div class="row mb-2 mb-sm-0 py-25">
                                <div class="d-none d-sm-block col-1">1</div>
                                <div class="col-9 col-sm-5">Room No - @Model.Booking.RoomNo</div>
                                <div class="d-none d-sm-block col-2">@Model.Booking.Quantity Days</div>
                                <div class="d-none d-sm-block col-2 text-95">@Model.Booking.Amount</div>
                                <div class="col-2 text-secondary-d2">@Model.Booking.TotalAmount</div>
                            </div>

                            @{
                                int x = 2;
                                foreach (var item in Model.Suplementary)
                                {
                                    <div class="row mb-2 mb-sm-0 py-25">
                                        <div class="d-none d-sm-block col-1">@x</div>
                                        <div class="col-9 col-sm-5">@item.Name</div>
                                        <div class="d-none d-sm-block col-2">@item.Quantity</div>
                                        <div class="d-none d-sm-block col-2 text-95">@item.Amount</div>
                                        <div class="col-2 text-secondary-d2">@item.TotalAmount</div>
                                    </div>
                                    x++;
                                }
                            }
                            @{
                                foreach (var item in Model.Complementary)
                                {
                                    <div class="row mb-2 mb-sm-0 py-25">
                                        <div class="d-none d-sm-block col-1">@x</div>
                                        <div class="col-9 col-sm-5">@item.Name</div>
                                        <div class="d-none d-sm-block col-2">@item.Quantity</div>
                                        <div class="d-none d-sm-block col-2 text-95">@item.Amount</div>
                                        <div class="col-2 text-secondary-d2">@item.TotalAmount</div>
                                    </div>
                                    x++;
                                }
                            }
                        </div>
                    </div>

                    <div class="row border-bottom brc-default-l2"></div>
                    <div class="row mt-3">
                        <div class="col-12 col-sm-7 text-grey-d2 text-95 mt-2 mt-lg-0">
                            Additionally 7.5% VAT will be include with total bill
                        </div>

                        <div class="col-12 col-sm-5 text-grey text-90 order-first order-sm-last">
                            <div class="row my-2">
                                <div class="col-7 text-right">
                                    SubTotal
                                </div>
                                <div class="col-5">
                                    <span class="text-120 text-secondary-d1" id="amount">@Model.Amount</span>
                                </div>
                            </div>

                            <div class="row my-2">
                                <div class="col-7 text-right">
                                    Tax (7.5%)
                                </div>
                                <div class="col-5">
                                    <span class="text-110 text-secondary-d1" id="vat">@Model.VAT</span>
                                </div>
                            </div>

                            <div class="row my-2 align-items-center bgc-primary-l3 p-2">
                                <div class="col-7 text-right">
                                    Total Amount
                                </div>
                                <div class="col-5">
                                    <span class="text-150 text-success-d3 opacity-2" id="totalAmount">@Model.TotalAmount</span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <hr />
                    <div>
                        <span class="text-secondary-d1 text-105">Thank you for staying with us</span>
                        <input type="submit" value="Pay Now" class="btn btn-info btn-bold px-4 float-right mt-3 mt-lg-0" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>