Models/Suplementary.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace HotelApplication.Models
{
    public class Suplementary
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Quantity { get; set; }

        [Column(TypeName = "decimal(18,2)")]
        public decimal Amount { get; set; }

        [Display(Name = "Total Amount")]
        [Column(TypeName = "decimal(18,2)")]
        public decimal TotalAmount { get; set; }
        public virtual ICollection<BookingSuplementary> Bookings { get; set; }

        [NotMapped]
        public virtual IEnumerable<Suplementary> Suplementaries { get; set; }
    }
}

Areas/Bookings/Controllers/SuplementaryController.cs
using HotelApplication.Models;
using HotelApplication.Database;
using HotelApplication.Services.Interface;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HotelApplication.Areas.Bookings.Controllers
{
    [Area("Bookings")]
    public class SuplementaryController : Controller
    {
        private readonly IRoomInformation<Suplementary> service;
        private readonly HotelDBContext context;
        private readonly IHostingEnvironment hostingEnvironment;

        public SuplementaryController(HotelDBContext context,
            IRoomInformation<Suplementary> service,
            IHostingEnvironment hostingEnvironment)
        {
            this.context = context;
            this.service = service;
            this.hostingEnvironment = hostingEnvironment;
        }

        public async Task<IActionResult> Index()
        {
            Suplementary data = new Suplementary
            {
                Suplementaries = await service.Get()
            };
            return View(data);
        }

        public async Task<IActionResult> Save(Suplementary model)
        {
            Suplementary suplementary = new Suplementary();
            if (model.Id != 0)
            {
                suplementary = await service.Details(model.Id);
            }
            suplementary.Suplementaries = await service.Get();
            return View(suplementary);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Save(Suplementary model, IFormFile Files)
        {
            if (ModelState.IsValid)
            {
                if (model.Id == 0)
                {
                    await service.Post(model);
                }
                else
                {
                    await service.Edit(model);
                }
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        public async Task<IActionResult> Details(int id = 0)
        {
            return View(await service.Details(id));
        }

        public async Task<IActionResult> Delete(int id)
        {
            var suplementary = await context.Suplementaries.FindAsync(id);
            await service.Delete(suplementary);
            return RedirectToAction(nameof(Index));
        }
    }
}

Areas/Bookings/Views/Suplementary/Details.cshtml
@model HotelApplication.Models.Suplementary

@{
    ViewData["Title"] = "Details";
    Layout = null;
}
<h4>Suplementary Service Details</h4>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-4"> @Html.DisplayNameFor(model => model.Name) </dt>
        <dd class="col-sm-8"> @Html.DisplayFor(model => model.Name) </dd>
        <dt class="col-sm-4"> @Html.DisplayNameFor(model => model.Quantity) </dt>
        <dd class="col-sm-8"> @Html.DisplayFor(model => model.Quantity) </dd>
        <dt class="col-sm-4"> @Html.DisplayNameFor(model => model.Amount) </dt>
        <dd class="col-sm-8"> @Html.DisplayFor(model => model.Amount) </dd>
        <dt class="col-sm-4"> @Html.DisplayNameFor(model => model.TotalAmount) </dt>
        <dd class="col-sm-8"> @Html.DisplayFor(model => model.TotalAmount) </dd>
    </dl>
</div>

Areas/Bookings/Views/Suplementary/Index.cshtml
@model HotelApplication.Models.Suplementary

@{
    ViewData["Title"] = "Suplementary Services";
}

<div class="row">
    <div class="col-md-6">
        <h3 class="h3">Suplementary Services</h3>
    </div>
    <div class="col-md-6">
        <div style="text-align:right;">
            <a asp-action="Save" class="btn btn-primary" style="width:300px;"><i class='bx bx-plus'></i> Suplementary Service</a>
        </div>
    </div>
</div>

<table class="table table-striped" style="margin-top:30px">
    <thead>
        <tr>
            <th> SL. </th>
            <th> @Html.DisplayNameFor(x => x.Name) </th>
            <th> @Html.DisplayNameFor(x => x.Quantity) </th>
            <th> @Html.DisplayNameFor(x => x.Amount) </th>
            <th> @Html.DisplayNameFor(x => x.TotalAmount) </th>
            <th class="text-center">Action</th>
        </tr>
    </thead>
    <tbody>
        @{
            var i = 1;
            foreach (var item in Model.Suplementaries)
            {
                <tr>
                    <td> @i. </td>
                    <td> @Html.DisplayFor(modelItem => item.Name) </td>
                    <td> @Html.DisplayFor(modelItem => item.Quantity) </td>
                    <td> @Html.DisplayFor(modelItem => item.Amount) </td>
                    <td> @Html.DisplayFor(modelItem => item.TotalAmount) </td>
                    <td class="text-center">
                        <a class="btn btn-sm btn-success" asp-action="Save" asp-route-id="@item.Id"><i class='bx bx-edit'></i></a> |
                        <a class="btn btn-sm btn-info text-white" onclick="showInPopup('@Url.Action("Details", "Suplementary", new { id = item.Id }, Context.Request.Scheme)')"><i class='bx bx-info-circle'></i></a> |
                        <a class="btn btn-sm btn-danger" onclick="Delete(@item.Id)" href="#"><i class='bx bx-trash'></i></a>
                    </td>
                </tr>
                i++;
            }
        }
    </tbody>
</table>

<script>
    function Delete(id) {
        location.replace("/Bookings/Suplementary/Delete/" + id);
    }
</script>

Areas/Bookings/Views/Suplementary/Save.cshtml
@model HotelApplication.Models.Suplementary

@{
    ViewData["Title"] = "Save";
}

<div class="row">
    <div class="col-md-1">
        <a asp-action="Index" class="btn btn-light" style="border-radius:50%"><i class='bx bx-arrow-back'></i></a>
    </div>
    <div class="col-md-5">
        <h3 class="h3">Suplementary Service</h3>
    </div>
</div>

<div class="container">
    <form asp-action="Save" enctype="multipart/form-data">
        <hr />
        <div class="row">
            <div class="col-md-12">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Id" />

                <div class="row form-group">
                    <label asp-for="Name" class="col-sm-3 control-label"></label>
                    <div class="col-sm-9">
                        <input asp-for="Name" class="form-control" />
                    </div>
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="row form-group">
                    <label asp-for="Quantity" class="col-sm-3 control-label"></label>
                    <div class="col-sm-9">
                        <input asp-for="Quantity" class="form-control" />
                    </div>
                    <span asp-validation-for="Quantity" class="text-danger"></span>
                </div>
                <div class="row form-group">
                    <label asp-for="Amount" class="col-sm-3 control-label"></label>
                    <div class="col-sm-9">
                        <input asp-for="Amount" class="form-control" />
                    </div>
                    <span asp-validation-for="Amount" class="text-danger"></span>
                </div>
                <div class="row form-group">
                    <label asp-for="TotalAmount" class="col-sm-3 control-label"></label>
                    <div class="col-sm-9">
                        <input asp-for="TotalAmount" class="form-control" />
                    </div>
                    <span asp-validation-for="TotalAmount" class="text-danger"></span>
                </div>
            </div>
        </div>
        <hr />
        <div class="form-group" style="text-align:center;">
            <input type="submit" value="Save" class="col-sm-6 btn btn-primary" style="border-radius:50px;" />
        </div>
    </form>
</div>